---
- name: ignore self
  ansible.builtin.set_fact:
    ignore: "{{ groups['self'] | difference([inventory_hostname]) | length < groups['self'] | length }}"

- name: configure sshd
  ansible.builtin.blockinfile:
    path: "/etc/ssh/sshd_config"
    marker: "# {mark} sshd {{ inventory_hostname }}"
    block: |
      PasswordAuthentication no
      AuthenticationMethods publickey
  register: sshd
  when: not ignore

- name: restart sshd
  ansible.builtin.systemd_service:
    name: sshd.service
    state: restarted
  when: not ignore

- name: generate key
  ansible.builtin.user:
    name: root
    generate_ssh_key: yes
  when: hostvars[inventory_hostname].sshcopy | default(False)

- name: backup key
  ansible.builtin.fetch:
    src: /root/.ssh/id_rsa.pub
    dest: ./tmp/sshcopy_rsa
    flat: yes
  when: hostvars[inventory_hostname].sshcopy | default(False)

- name: copy key
  ansible.builtin.blockinfile:
    block: "{{ lookup('ansible.builtin.file', './tmp/sshcopy_rsa') }}"
    path: /root/.ssh/authorized_keys
    marker: "# {mark} root@{{ inventory_hostname }}"
  when: not hostvars[inventory_hostname].sshcopy | default(False) and not ignore

- name: delete known_hosts
  ansible.builtin.file:
    path: /root/.ssh/known_hosts
    state: absent
  when: hostvars[inventory_hostname].sshcopy | default(False)
