---
- name: dilate updates and packages
  hosts: sfw_new
  remote_user: root
  tasks:
    # todo these task only run 1ce wat else can b moved here???
    # todo change sshd settings
    # todo enable ufw
    # todo add ufw rule
    - name: full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: install wireguard
      community.general.pacman:
        name: wireguard-tools
        state: present

    - name: install git
      community.general.pacman:
        name: git
        state: present

    - name: install docker
      community.general.pacman:
        name: docker
        state: present

    - name: enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        # state: started

    - name: install golang
      community.general.pacman:
        name: go
        state: present

    - name: create user
      ansible.builtin.user:
        name: sfw
        group: wheel
        groups: docker
        generate_ssh_key: yes

    - name: dilate sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "Same thing without a password"
        line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"

    - name: install local pubkey on hosts
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa.pub"
        dest: /home/sfw/.ssh/authorized_keys
        owner: sfw
        group: wheel
        mode: '0600'

    # todo no reboot option
    - name: reboot
      ansible.builtin.reboot:

    # todo pretty sure i can build here

    - name: clone sfw
      remote_user: sfw
      ansible.builtin.git:
        repo: 'https://github.com/Sife-ops/sfw.git'
        dest: '/home/sfw/sfw'
        recursive: yes
        update: true

    - name: pull image
      remote_user: sfw
      community.docker.docker_image:
        name: itzg/minecraft-server
        source: pull
