---
- name: dilate updates and packages
  hosts: sfw
  remote_user: root
  tasks:
    - name: configure sshd
      ansible.builtin.blockinfile:
        insertafter: "^#PasswordAuthentication"
        path: "/etc/ssh/sshd_config"
        block: |
          PasswordAuthentication no
          AuthenticationMethods publickey
      register: sshd

    - name: restart sshd
      ansible.builtin.systemd_service:
        name: sshd.service
        state: restarted
      when: sshd.changed

    - name: populate service facts
      ansible.builtin.service_facts:
    # todo standard ufw settings no work with wireguard
    - name: disable firewall
      ansible.builtin.systemd_service:
        name: ufw.service
        enabled: false
        state: stopped
      when: ansible_facts.services['ufw.service'] is defined