---
- name: dilate updates and packages
  hosts: sfw_node_new
  remote_user: root
  tasks:

###############################################################################
###############################################################################
###############################################################################

###############################################################################
## NOT DRY NOT DRY NOT DRY NOT DRY NOT DRY NOT DRY NOT DRY NOT DRY NOT DRY N ##
###############################################################################

    - name: configure sshd
      ansible.builtin.blockinfile:
        insertafter: "^#PasswordAuthentication"
        path: "/etc/ssh/sshd_config"
        block: |
          PasswordAuthentication no
          AuthenticationMethods publickey

    - name: restart sshd
      ansible.builtin.systemd_service:
        name: sshd.service
        enabled: true
        state: started

    # todo standard settings no work with wireguard
    - name: disable firewall
      ansible.builtin.systemd_service:
        name: ufw.service
        enabled: false
        state: stopped

###############################################################################
###############################################################################
###############################################################################

    - name: full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: install wireguard
      community.general.pacman:
        name: wireguard-tools
        state: present
    - name: install golang
      community.general.pacman:
        name: go
        state: present
    - name: install docker
      community.general.pacman:
        name: docker
        state: present
    - name: enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        # state: started

###############################################################################
###############################################################################
###############################################################################

    - name: create user
      ansible.builtin.user:
        name: sfw
        group: wheel
        groups: docker
        generate_ssh_key: yes

    - name: install your pubkey
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa.pub"
        dest: /home/sfw/.ssh/authorized_keys
        owner: sfw
        group: wheel
        mode: '0600'

    - name: install manager pubkey
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './tmp/sfw_manager_rsa') }}"
        path: /home/sfw/.ssh/authorized_keys
        backup: yes

    - name: configure sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "Same thing without a password"
        line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"

    - name: reboot
      ansible.builtin.reboot:
