---
- name: update & create user
  hosts: managed
  remote_user: root
  tasks:
    - name: full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: install git
      community.general.pacman:
        name: git
        state: present
    - name: install docker
      community.general.pacman:
        name: docker
        state: present
    - name: enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
    - name: install golang
      community.general.pacman:
        name: go
        state: present
    - name: create user
      ansible.builtin.user:
        name: sfw
        group: wheel
        groups: docker
        generate_ssh_key: yes
    - name: dilate ssh
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa.pub"
        dest: /home/sfw/.ssh/authorized_keys
        owner: sfw
        group: wheel
        mode: '0600'
    - name: reboot
      ansible.builtin.reboot:
