---
- name: installing sfw
  hosts: managed
  remote_user: sfw
  tasks:
    - name: clone sfw
      ansible.builtin.git:
        repo: 'https://github.com/Sife-ops/sfw.git'
        dest: '/home/sfw/sfw'
