---
# can prolly move this to 000
# recurse submodules!@!!
- name: installing sfw
  hosts: sfw
  remote_user: sfw
  tasks:
    - name: clone sfw
      ansible.builtin.git:
        repo: 'https://github.com/Sife-ops/sfw.git'
        dest: '/home/sfw/sfw'
        force: true
