---
- name: create sfw user and install local pubkey on it
  hosts: sfw
  remote_user: root
  tasks:
    - name: create user
      ansible.builtin.user:
        name: sfw
        group: wheel
        groups: docker
        generate_ssh_key: yes

    # local pubkey for root has already been copied by ur provider
    - name: install local pubkey on sfw user
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', lookup('ansible.builtin.env', 'HOME') + '/.ssh/id_rsa.pub') }}"
        path: /home/sfw/.ssh/authorized_keys
        backup: yes
