---
- name: dilate updates and packages (continued)
  hosts: sfw_new
  remote_user: sfw
  tasks:
    - name: clone sfw
      ansible.builtin.git:
        repo: 'https://github.com/Sife-ops/sfw.git'
        dest: '/home/sfw/sfw'
        recursive: yes
        update: true

    - name: build & install cubiomes
      ansible.builtin.shell:
        chdir: /home/sfw/sfw/cubiomes
        cmd: "make && make g0 && cp ./a.out ../bin/cubiomes"

    - name: compile sfw
      ansible.builtin.shell:
        chdir: /home/sfw/sfw
        cmd: "make all"

    - name: pull image
      community.docker.docker_image:
        name: itzg/minecraft-server
        source: pull
