---
- name: configure sshd, create new user
  hosts: sfw_manager:sfw_node
  remote_user: root
  # gather_facts: no
  tasks:

###############################################################################
## sshd

    - name: configure sshd
      ansible.builtin.blockinfile:
        path: "/etc/ssh/sshd_config"
        insertafter: "^#PasswordAuthentication"
        marker: "# {mark} sshd {{ inventory_hostname }}"
        block: |
          PasswordAuthentication no
          AuthenticationMethods publickey
      register: sshd

    - name: restart sshd
      ansible.builtin.systemd_service:
        name: sshd.service
        state: restarted
      when: sshd.changed

################################################################################
## sfw user

    - name: create sfw user
      ansible.builtin.user:
        name: sfw
        group: sudo
        generate_ssh_key: yes

    # local pubkey for root has already been copied by ur provider
    - name: install local pubkey on sfw user
      ansible.builtin.blockinfile:
        path: /home/sfw/.ssh/authorized_keys
        create: true
        backup: yes
        marker: "# {mark} local pubkey {{ inventory_hostname }}"
        block: "{{ lookup('ansible.builtin.file', lookup('ansible.builtin.env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: set up ssh for manager
  hosts: sfw_manager
  remote_user: root
  tasks:
    - name: generate ssh key for root
      ansible.builtin.user:
        name: root
        generate_ssh_key: yes

    - name: backup manager ssh pubkey (sfw)
      ansible.builtin.fetch:
        src: /home/sfw/.ssh/id_rsa.pub
        dest: ./tmp/sfw_manager_rsa_sfw
        flat: yes
    - name: backup manager ssh pubkey (root)
      ansible.builtin.fetch:
        src: /root/.ssh/id_rsa.pub
        dest: ./tmp/sfw_manager_rsa_root
        flat: yes

    - name: delete ssh known hosts (sfw)
      ansible.builtin.file:
        path: /home/sfw/.ssh/known_hosts
        state: absent
    - name: delete ssh known hosts (root)
      ansible.builtin.file:
        path: /root/.ssh/known_hosts
        state: absent

- name: set up ssh for nodes
  hosts: sfw_node
  remote_user: root
  tasks:
    - name: install manager ssh pubkeys (sfw)
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './tmp/sfw_manager_rsa_sfw') }}"
        path: /home/sfw/.ssh/authorized_keys
        marker: "# {mark} manager sfw pubkey to sfw {{ inventory_hostname }}"
        backup: yes
    - name: install manager ssh pubkeys (sfw)
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './tmp/sfw_manager_rsa_sfw') }}"
        path: /root/.ssh/authorized_keys
        marker: "# {mark} manager sfw pubkey to root {{ inventory_hostname }}"
        backup: yes

    - name: install manager ssh pubkeys (root)
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './tmp/sfw_manager_rsa_root') }}"
        path: /home/sfw/.ssh/authorized_keys
        marker: "# {mark} manager root pubkey to sfw {{ inventory_hostname }}"
        backup: yes
    - name: install manager ssh pubkeys (root)
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './tmp/sfw_manager_rsa_root') }}"
        path: /root/.ssh/authorized_keys
        marker: "# {mark} manager root pubkey to root {{ inventory_hostname }}"
        backup: yes