---
- name: install nfs server on manager
  hosts: sfw_manager
  remote_user: root
  # gather_facts: no
  tasks:

    # - name: end
    #   meta: end_play

    - name: install nfs server
      ansible.builtin.package:
        name: nfs-kernel-server
        state: present

    - name: create nfs export dir
      ansible.builtin.file:
        path: /var/nfs/sfw
        state: directory
        owner: nobody # todo use sfw?
        group: nogroup # todo use sudo?
        mode: '0777'

    - name: configure nfs
      ansible.builtin.blockinfile:
        path: /etc/exports
        create: true
        mode: '0644'
        marker: "# {mark} nfs {{ inventory_hostname }}"
        block: |
          /var/nfs/sfw 10.0.0.0/24(rw,sync,no_subtree_check)

    - name: start/enable nfs
      ansible.builtin.systemd_service:
        name: nfs-kernel-server
        enabled: true
        state: restarted

- name: mount nfs export on nodes
  hosts: sfw_node:self # todo and self?
  remote_user: root
  become: true
  # gather_facts: no
  tasks:

    - name: mount nfs export
      ansible.posix.mount:
        path: /tmp/sfw_nfs
        src: "{{ hostvars[groups['sfw_manager'][0]].wgip }}:/var/nfs/sfw"
        fstype: nfs
        opts: vers=4
        # todo add to node fstab?
        # state: present
        # state: mounted
        state: ephemeral