---
- name: install updates and packages for nodes
  hosts: sfw_node
  remote_user: root
  tasks:
    - name: full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: install wireguard
      community.general.pacman:
        name: wireguard-tools
        state: present
    - name: install golang
      community.general.pacman:
        name: go
        state: present
    - name: install docker
      community.general.pacman:
        name: docker
        state: present
    - name: enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        # state: started

    - name: configure sudo for a node
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "Same thing without a password"
        line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"

    # todo 'force reboot' extra option
    # check for 'rebooted' file
    - name: check if the computer has ever rebooted
      ansible.builtin.stat:
        path: "/root/has_rebooted"
      register: stat_rebooted

    - name: reboot
      ansible.builtin.reboot:
        path: /root/has_rebooted
      when: not stat_rebooted.stat.exists

    - name: remember this reboot
      ansible.builtin.file:
        path: /root/has_rebooted
      when: not stat_rebooted.stat.exists

