---
- name: pre-reboot (node)
  hosts: sfw_node
  remote_user: root
  tasks:

    # - name: asdf2
    #   debug:
    #     var: reboot
    # - name: stop
    #   meta: end_play

    - name: full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: install wireguard
      community.general.pacman:
        name: wireguard-tools
        state: present
    - name: install golang
      community.general.pacman:
        name: go
        state: present
    - name: install docker
      community.general.pacman:
        name: docker
        state: present
    - name: enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        # state: started
    - name: add sfw to docker group
      ansible.builtin.user:
        name: sfw
        groups: docker

    - name: check if the computer has ever rebooted
      ansible.builtin.stat:
        path: /root/has_rebooted
      register: stat_rebooted

    - name: reboot
      ansible.builtin.set_fact:
        reboot: False
      when: reboot is undefined
    - name: reboot
      ansible.builtin.reboot:
      when: reboot or (not stat_rebooted.stat.exists)

    - name: remember this computer has rebooted
      ansible.builtin.file:
        path: /root/has_rebooted
        state: touch
      when: not stat_rebooted.stat.exists
