---
- name: start postgres (manager)
  hosts: sfw_manager
  remote_user: root
  tasks:
    - name: install manager tools
      ansible.builtin.apt:
        pkg:
          - tmux
          - postgresql-client
          - python3-psycopg


    - name: create pg_hba.conf
      ansible.builtin.blockinfile:
        path: /home/sfw/pg_hba.conf
        create: true
        block: |
          local   all             all                                     trust
          host    all             all             127.0.0.1/32            trust
          host    all             all             ::1/128                 trust
          local   replication     all                                     trust
          host    replication     all             127.0.0.1/32            trust
          host    replication     all             ::1/128                 trust
          host    all             all             10.0.0.0/24             trust
          host    all             all             all                     scram-sha-256

    - name: start postgres docker
      community.docker.docker_container:
        name: sfw-db
        image: postgres
        image_name_mismatch: ignore
        state: started
        command: "postgres -c 'hba_file=/etc/postgresql/pg_hba.conf'"
        volumes:
          - "/home/sfw/pg:/var/lib/postgresql/data"
          - "/home/sfw/pg_hba.conf:/etc/postgresql/pg_hba.conf"
        ports:
          - "0.0.0.0:5432:5432"
        env:
          POSTGRES_USER: seed
          # ALTER USER seed WITH PASSWORD 'new_password';
          POSTGRES_PASSWORD: seed 
          POSTGRES_DB: seed
          PGDATA: "/var/lib/postgresql/data/pgdata"

    - name: wait for postgres docker to start
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 5432
