---
- name: clone sfw repository
  hosts: sfw_manager:sfw_node
  remote_user: sfw
  tasks:
    - name: clone sfw
      ansible.builtin.git:
        repo: https://github.com/Sife-ops/sfw.git
        dest: /home/sfw/sfw
        recursive: yes
        update: true

    # - name: copy hosts file
    #   ansible.builtin.copy:
    #     src: "./hosts"
    #     dest: "/home/sfw/sfw/ansible/hosts"
    #     force: false
