---
- name: compile sources, pull mcs container
  hosts: sfw_node
  remote_user: sfw
  tasks:
    # - name: build & install cubiomes
    #   ansible.builtin.shell:
    #     chdir: /home/sfw/sfw/cubiomes
    #     cmd: "make && make g0 && cp ./a.out ../bin/cubiomes"

    - name: compile sfw
      ansible.builtin.shell:
        chdir: /home/sfw/sfw
        cmd: "make all"

    - name: pull docker image for minecraft server
      community.docker.docker_image:
        name: itzg/minecraft-server
        source: pull
