---
- name: update et al.
  hosts: sfw
  remote_user: root
  tasks:
    - name: full system upgrade
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: install git
      community.general.pacman:
        name: git
        state: present

    - name: install docker
      community.general.pacman:
        name: docker
        state: present

    - name: enable docker
      ansible.builtin.systemd_service:
        name: docker.service
        enabled: true
        # state: started

    - name: install golang
      community.general.pacman:
        name: go
        state: present

    - name: create user
      ansible.builtin.user:
        name: sfw
        group: wheel
        groups: docker
        generate_ssh_key: yes

    - name: dilate sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: "Same thing without a password"
        line: "%wheel ALL=(ALL:ALL) NOPASSWD: ALL"

    - name: dilate ssh
      ansible.builtin.copy:
        src: "{{ lookup('ansible.builtin.env', 'HOME') }}/.ssh/id_rsa.pub"
        dest: /home/sfw/.ssh/authorized_keys
        owner: sfw
        group: wheel
        mode: '0600'

    - name: clone sfw
      remote_user: sfw
      ansible.builtin.git:
        repo: 'https://github.com/Sife-ops/sfw.git'
        dest: '/home/sfw/sfw'
        recursive: yes
        update: true

    # todo pretty sure i can build here

    - name: reboot
      ansible.builtin.reboot:

- name: update et al.
  hosts: sfw
  remote_user: sfw
  tasks:
    - name: pull image
      community.docker.docker_image:
        name: itzg/minecraft-server
        source: pull

- name: dilate manager
  hosts: sfw_manager
  remote_user: sfw
  tasks:
    - name: install ansible
      remote_user: root
      community.general.pacman:
        name: ansible
        state: present
    - name: install ansible-core
      remote_user: root
      community.general.pacman:
        name: ansible-core
        state: present

    - name: dilate ansible1
      remote_user: root
      ansible.builtin.file:
        path: /etc/ansible
        state: directory
    - name: dilate ansible2
      remote_user: root
      ansible.builtin.copy:
        src: /etc/ansible/hosts
        dest: /etc/ansible/hosts

    - name: install tmux
      remote_user: root
      community.general.pacman:
        name: tmux
        state: present

    - name: install postgresql
      remote_user: root
      community.general.pacman:
        name: postgresql
        state: present

    - name: dilate ssh
      ansible.builtin.fetch:
        src: /home/sfw/.ssh/id_rsa.pub
        dest: ./tmp/sfw_manager_rsa
        flat: yes

    - name: dilate docker
      community.docker.docker_container:
        name: sfw-db
        image: postgres
        # pull: true
        state: started
        volumes:
          - "/home/sfw/pg:/var/lib/postgresql/data"
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: "todo000"
          POSTGRES_USER: "todo000"
          POSTGRES_DB: "todo000"
          PGDATA: "/var/lib/postgresql/data/pgdata"

- name: dilate managed
  hosts: sfw_managed
  remote_user: sfw
  tasks:
    - name: dilate ssh
      ansible.builtin.blockinfile:
        block: "{{ lookup('ansible.builtin.file', './tmp/sfw_manager_rsa') }}"
        path: /home/sfw/.ssh/authorized_keys
        backup: yes