---
- name: backup postgres files
  hosts: sfw_manager
  remote_user: root
  tasks:
    - name: stop postgres
      community.docker.docker_container:
        name: sfw-db
        state: stopped
    - name: create archive
      ansible.builtin.shell:
        cmd: "tar -cvpf sfw-db-latest.tar pg"
        chdir: /home/sfw
    - name: download archive
      ansible.builtin.fetch:
        src: /home/sfw/sfw-db-latest.tar
        dest: ./tmp/
        flat: yes

- import_playbook: 12.yml


# - name: transfer postgres files
#   hosts: sfw_manager_dest
#   remote_user: root
#   tasks:
#     - name: upload postgres archive
#       ansible.builtin.copy:
#         src: ./tmp/sfw-db-latest.tar
#         dest: /home/sfw/
