#!/usr/bin/env ansible-playbook
---
- name: play 1
  hosts: all
  # gather_facts: no
  remote_user: root
  roles:

    - role: sshcopy
      tags:
        - sshcopy

    - role: wireguard
      tags:
        - wireguard

    - role: nfs
      tags:
        - nfs
