#!/usr/bin/env ansible-playbook
---
- name: play 1
  hosts: all
  # gather_facts: no
  remote_user: root

  roles:
    - role: wireguard
      tags:
        - wireguard

    - role: nfs
      tags:
        - nfs

- name: play 2
  hosts: sfw_manager:sfw_node
  # gather_facts: no
  remote_user: root

  pre_tasks:
    - name: create user
      ansible.builtin.user:
        name: sfw
        group: sudo
        generate_ssh_key: yes

  # - name: install manager tools
  #   ansible.builtin.apt:
  #     pkg:
  #       - tmux
  #       - postgresql-client
  #       - python3-psycopg

  roles:
    - role: sshcopy
      tags:
        - sshcopy

    - role: swap
      tags:
        - swap

    - role: postgres
      tags:
        - postgres

    # - role: docker
    #   tags:
    #     - docker