#!/usr/bin/env ansible-playbook
---
- name: play 1
  hosts: all
  gather_facts: no
  roles:

    - role: wireguard
      tags:
        - wireguard

    # - role: sshcopy
    #   tags:
    #     - sshcopy

    # - role: nfs
    #   tags:
    #     - nfs
