#!/usr/bin/env ansible-playbook
---
- name: play 1
  hosts: all
  roles:

    - role: wireguard
      tags:
        - wireguard

    - role: ssh
      tags:
        - ssh

    - role: ssh
      username: sfw
      tags:
        - ssh
